import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} font-roboto`}>
        {/* Change defaultTheme to "light" */}
       <ThemeProvider
          attribute="class"
          defaultTheme="light" // This is correct. It sets the theme if NO localStorage value is found.
          enableSystem={false} // Temporarily disable to simplify debugging
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

